apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-food
  labels:
    app: app-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-food
  template:
    metadata:
      labels:
        app: app-food
    spec:
      containers:
      - name: app-food
        image: youego/app-food  
        env:
        - name: MONGO_URI          
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-hub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-food-svc
spec:
  type: NodePort
  selector:
    app: app-food
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30301